### ISSUE TITLE
Wrong or missing translation

### ISSUE THREAD

**Issue by dt-92** [MudBlazor/Translations#23]
Some string are missing from the translation package . like
loading... , no item found, row found , <> of the <>,....

**Comment by meenzen** [comment]
As per the Localization docs:

> Note: Some components don't support localization yet. Contributions are welcome!

This package contains all translation keys currently available and will be updated once more are added. If you want to have a specific component translated, please open an issue for that component in the MudBlazor repo.

**Comment by dt-92** [comment]
actually i need to get  the translation to the MudDataGridPager and MudTableGridPager
public sealed class AppDataGridPager<T> : MudDataGridPager<T>
{
	protected override void OnParametersSet()
	{
		AllItemsText = "Tous";
		RowsPerPageString = "Lignes par page";
		PageSizeOptions = [10, 20, 50, 100, 500];
		InfoFormat = "{first_item}-{last_item} de {all_items}";
		base.OnParametersSet();
	}

**Comment by meenzen** [comment]
So what is the issue? They're already translated.

**Comment by dt-92** [comment]
I Saw in the translation , but it 'not functioning . the column sort order is ok but not de pager

**Comment by meenzen** [comment]
I can only help you If you explain what your issue is. Please elaborate:

- Which language are you using
- What are you expecting to happen
- What is actually happening
- Add a screenshot

**Comment by dt-92** [comment]
hello ,  I'm using c#  in french language.
First screenshot show the translation is active in the datagrid column
![image](https://github.com/user-attachments/assets/5a0c9cce-1a75-4484-8af9-8efa8ab2dfd0)

in my second screenshot the first row show my own overload of the pager  the second row is  standard line of the pager without tranlsation
![image](https://github.com/user-attachments/assets/b591a80f-ad3c-4c79-8f93-b52958a2487e)

the code of my pager is
public sealed class AppDataGridPager<T> : MudDataGridPager<T>
{
	protected override void OnParametersSet()
	{
		AllItemsText = "Tous";
		RowsPerPageString = "Lignes par page";
		PageSizeOptions = [10, 20, 50, 100, 500];
		InfoFormat = "{first_item}-{last_item} de {all_items}";
		base.OnParametersSet();
	}
}

**Comment by meenzen** [comment]
The relevant changes were added in 3673fe205297e7ff5a973de6576a4bc8e9adea2f which was not released yet.

Please upgrade to the new release `v1.1.0` which includes these translations.

**Comment by dt-92** [comment]
It is ok 
Thanks for the reactivity.
