### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by MathSzoke** [MudBlazor/Translations#26]
I've tested the language change code, but when I change the language, the page just reloads and doesn't change the language of the text to the selected language.
![image_2024-07-25_003821099](https://github.com/user-attachments/assets/0ad15cfa-e90f-4f32-a1dd-74f9d53153c3)

**Comment by meenzen** [comment]
The text on that example page is not made to be translated. The package `MudBlazor.Translations` only includes translations for the MudBlazor components. If you use e.g. a DataGrid you should see that the "Rows per page:" text is translated.
